apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
      ## Please update the image name
        image: mahendrshinde/tomcat-redisson-session:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: myapp
              optional: false
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
